Add in ability to customize 'next' button
danielstorey/adapt-stacklist pull request #6
Opened 2017-02-07 18:30 UTC by adamlesniak

I've added in ability to customise the next button wording - it's connected to each ``adapt-stacklist`` item.

Reasons for that:

- Word 'next' was hard coded onto the component core - making it troublesome during possible translation.
- It can make this component more engaging by further customisation.

Any questions suggestions - please let me know! 

Thanks,
Adam

2017-02-07 18:46 UTC, danielstorey requested changes
Hi Adam,

Thanks for your contribution - really good idea! The only problem with these changes are they are not backwards-compatible. So...

Can I suggest we retain the body property and the logic in the template (which allows for string arrays in the json) instead of changing to description. And maybe have the button text default to "Next" when the next property is not defined.

This will keep all existing users happy :)

Are you happy to make those changes or do you want me to make them?

Thanks again for contributing to making this component better! :)

2017-02-07 21:18 UTC, adamlesniak commented
Thanks Daniel,

You're right - that's what I thought after submitting this PR - will implement it later this week.

Adam

2017-02-08 11:16 UTC, adamlesniak commented
Just added in backwards compatibility.

Word 'Next' is still hard coded in the component - alternatively we could pull it from Aria labels, but I don't see this as perfect solution - will leave that decision to you.

Adam

2017-02-08 11:18 UTC, simondate commented
The starting button has the hardcoded use of the word 'Click here to begin'. Is there a way to customise this too?

2017-02-08 11:24 UTC, merged

2017-02-08 12:47 UTC, danielstorey commented
See the latest update including updates to example.json and readme. Added a _button property very similar to trickle so now you can specify the start text, and the continue text for individual items or all items that aren't specified individually. If you don't specify anything at all for _button or either child property the defaults take over.